config/routes.rb
Rails.application.routes.draw do
  resources :articles, :admins, :sessions, :photos, :stats
  get 'stats/create'

  get 'stats/destroy'

  get 'create/destroy'

  
  get 'photos/create'

  get 'photos/destroy'

  get 'photos/new'

  get 'photos/update'

  get 'admins/new'
  get "log_in" => "sessions#new", :as =>'log_in'
  get "log_out" => "sessions#destroy", :as => 'log_out'
  get "/fetch_articles" => 'articles#from_category', as: 'fetch_articles'
  get "/next_articles" => "articles#next_articles", as: "next_articles"
  get "/previous_articles" => "articles#previous_articles", as: "previous_articles"
  get 'welcome/index'

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessor :password
	has_many :stats
	before_save :encrypt_password
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :username
	validates_uniqueness_of :username


	def self.authenticate(username,password)
		admin = find_by_username(username)
		if admin && admin.password_hash == BCrypt::Engine.hash_secret(password,admin.password_salt)
			admin
		else 
			nil
		end
	end
	def encrypt_password
		if password.present? 
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
			password_hash
		end
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,length: {minimum: 5}
	validates :text, presence: true, length: {minimum: 5}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessor :file_data
	require 'carrierwave/orm/activerecord'
	mount_uploader :file_data, PhotoUploader
	validates :file_data, presence: true
	validates :title, presence: true
end

app/models/stat.rb
class Stat < ActiveRecord::Base
	belongs_to :admin 
	validates :hours_slept, presence:true
	validates :hours_worked, presence:true
	validates :day_rating, presence:true
	validates :hours_fitness, presence:true
	validates :mg_caffeine, presence:true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	def new 
		@admin = Admin.new
		render 'new'
	end
	def create
		@admin = Admin.new(admin_params)
		if Admin.all().length>=1
			render 'new', :notice=>"nice try"
		elsif @admin.save
			redirect_to root_url, :notice => "Welcome"
		end
	end
	def index
		caffeine=[]
		hours_slept=[]
		hours_worked=[]
		day_ratings=[]
		@admin = Admin.first
		@stat = Stat.new()
		@stats=Stat.all();
		
	end
	private 

	def admin_params
		params.require(:admin).permit(:username,:password,:password_confirmation)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_admin


  private 

  def current_admin
  	@current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	attr_accessor :date
	before_action :admin?,only:[:new,:destroy,:update,:edit,:create]

	def create
		@article = Article.new(article_params)
		@article.date = Time.now.strftime("%b %Y")
		if @article.save
			redirect_to @article
		else
			render 'new', :error =>"Could not submit"
		end
	end
	def destroy
		@article = Article.find_by_id(params[:id])
		@article.destroy
		redirect_to articles_path
		# redirect_to @article
	end
	def new 
		@article = Article.new()
	end
	def show
		@article = Article.find(params[:id])
		@photos = Photo.all();
	end

	def index
		@articles = Article.order(created_at: :desc)
		@times = dates(@articles)
	end
	def edit 
		@article = Article.find(params[:id])
	end
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		if @article.update(article_params)
			redirect_to @article
		else 
			render "edit"
		end
	end

	def from_category
		@selected_articles = Article.where("date = ?",params[:time])
		respond_to do |format|
			format.js
			format.html{redirect_to(articles_path)}
		end
	end
	def next_articles
		@articles = Article.order(created_at: :desc)[params[:index].to_i..params[:index].to_i+5]
		respond_to do |format|
			format.js
			format.html{redirect_to(articles_path)}
		end
	end
	def previous_articles
		@articles = Article.order(created_at: :desc)[params[:index].to_i-10..params[:index].to_i]
		respond_to do |format|
			format.js
			format.html{redirect_to(articles_path)}
		end
	end

	private 
	def admin? 
		if !current_admin 
			redirect_to root_path, :notice => "you are not the admin"
		end
	end

	def article_params
		params.require(:article).permit(:title,:text,:description,:tags,:date)
	end

	def dates(articles)
		dates = []
		articles.each do |article|
			dates << article.created_at
		end
		dates
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :admin?,only:[:new,:destroy,:update,:edit,:create]
	def create
		@photo =Photo.new(photo_params)
		@photo.file_data = params[:file]
		if @photo.save!
			redirect_to photos_path, :notice => 'image upload successful'
		else 
			render 'new'
		end
	end
	def index
		
		@photos = Photo.all()
	end
	def edit
		@photo = Photo.find(params[:id])
	end
	def update
		@photo = Photo.find(params[:id])
		if @photo.save
			redirect_to photos_path, :notice => "update successful"
		else
			render 'new', :notice => "update not successful"
		end
	end
	def destroy 
		@photo = Photo.find(params[:id])
		if @photo.delete 
			redirect_to photos_path, :notice => "photo deleted"
		else 
			render photos_path, :notice => "Unable to delete photo"
		end
	end
	def new 
		@photo = Photo.new()
	end
end

private 
	def photo_params
		params.require(:photo).permit(:title,:description,:file_data,:tags)
	end
	def admin?
		unless current_admin 
			flash[:error] = "You are not an admin"
			redirect_to photos_path
		end
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		admin = Admin.authenticate(params[:username],params[:password])
		if admin
			session[:admin_id] = admin.id
			redirect_to root_url, :notice => "logged in"
		else
			flash.now.alert= "could not create session"
			render 'new'
		end
	end
	def destroy
		session[:admin_id] = nil
		redirect_to root_url, :notice=> 'logged out'
	end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
	before_action :admin?,only:[:new,:destroy,:update,:edit,:create]
	def create
		@stat = Stat.new(stats_params)
		if @stat.save!
			redirect_to root_path
		end
	end
	def destroy
		@stat = Stat.find_by_id(params[:id])
		@stat.delete!
	end
	def new 
		@stat = Stat.new()
	end
	private 

	def stats_params
		params.require(:stat).permit(:hours_worked,:hours_slept,:hours_fitness,:mg_caffeine,:day_rating)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@articles = Article.order(date: :asc);
  	@photos = Photo.order(created_at: :asc);
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/index.html.erb
<div id="container">

	<div id="lights">
		<br>
		
		<div class="wrap">
			<%=image_tag "cathedral.JPG",:id=> "profile-img"%>

			<% if current_admin%>
			<%= render :partial=> '/stats/form'%>
			<%else%>
			<div class="wrap">
				<div id='updates'>
					<h2 class="gold">About Me</h2>
					<p>Sed semper dictum auctor. Proin nisl augue, venenatis et nulla eget, suscipit gravida lacus. Duis at libero consequat, ultrices arcu vel, lacinia lorem. Nullam dapibus, nunc non placerat gravida, felis augue viverra neque, eu hendrerit eros erat a risus. Duis pretium congue enim. Phasellus in ullamcorper diam. Nulla facilisi. In ut quam consequat, fermentum ante eu, eleifend lectus. Integer porttitor, mi a tristique tincidunt, ipsum libero lacinia orci, sed sodales nibh dolor at dolor.</p>
				</div>
			</div>
			<%end%>
		</div>
	</div>

	<div class="wrap" id ="graph">
		<div id="stats-updates">
<!-- Seriously need to move this logic elsewhere -->
			<%caffeine=[]%>
			<%sleep=[]%>
			<%work = []%>
			<%day =[]%>
			<%fitness=[]%>
			<%@stats.each do |stat|%>
				<% caffeine << [stat.created_at.to_date,stat.mg_caffeine/100]%>
				<% sleep << [stat.created_at.to_date,stat.hours_slept]%>
				<% work << [stat.created_at.to_date,stat.hours_worked]%>
				<% day << [stat.created_at.to_date,stat.day_rating]%>
				<% fitness << [stat.created_at.to_date,stat.hours_fitness]%>

			<%end%>	
			<h3 class="gold">Activity Chart</h3>
			<%= line_chart [
				{:name=>"caffeine", :data=>caffeine},
				{:name=>"sleep",:data=>sleep},
				{:name=>"work",:data=>work},
				{:name=>"day",:data=>day},
				{:name=>"fitness",:data=>fitness}
			],library:{title:"Activity Tracker",backgroundColor:"black"} %>
		</div>

		
		
		
	</div>

</div>

app/views/admins/new.html.erb
<h1>Sign Up</h1>
<%=form_for @admin do |f|%> 
	<% if @admin.errors.any?%>
		<h3>We found the following errors:</h3>
		<ul>
		<% @admin.errors.full_messages.each do |msg| %>
			<li><%=msg%></li>
		<%end%>

		</ul>
	<%end%>
	<p><%=f.label :username%>
		<%=f.text_field :username%></p>
	<p><%=f.label :password%>
		<%=f.password_field :password%></p>
	<p><%=f.label :password_confirmation%>
	<%=f.password_field :password_confirmation%></p>
	<p class="submit"><%=f.submit%></p>
<%end%>

app/views/admins/show.html.erb
<div id="container">
	<h1 class="gold">Welcome Jordan!</h1>

	<div class="wrap">
		<%=image_tag "cathedral.JPG",:id=> "profile-img"%>
		<%= render :partial=> '/stats/form'%>
	</div>

	<div class="wrap" id ="graph">
		<div id="stats-updates">
			<h1>Place graph of stats here</h1>
		</div>
		
	</div>

</div>

app/views/articles/_article_list.html.erb
	<tr>
		<th>Title</th>
		<th>Date</th>
		<% if current_admin%>
			<th>Options</th>
		<%end%>
	</tr>
	<% items.each do |item| %>
	<tr>
	  <td><%= link_to "#{item.title}", article_path(item) %></td>      
	  <td><%=item.created_at.to_formatted_s(:long)%></td>
	  <% if current_admin %>
	  	<td><%=link_to 'edit', edit_article_path(item)%><%=link_to 'delete',article_path(item), method: :delete%></td>
	  <%end%>
	</tr>
	<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<h1><%=yield(:title)%></h1>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <h3><%= f.label :title %></h3>
    
    <%= f.text_field :title %>
  <h3><%=f.label :description %></h3>
    <%=f.text_field :description%>
  <p>
    <h3><%= f.label :text %></h3><br>
    <%= f.text_area :text %>
  </p>
  <br>
  <h3><%=f.label :tags%></h3><br>
  <%=f.text_field :tags%><br>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<%provide :title , "Edit"%>
<%= render 'form'%>
<%= link_to 'Back', articles_path %>

app/views/articles/from_category.js.erb
$("#ajax-table").html("<%= escape_javascript(render partial: 
	'article_list', locals: { items: @selected_articles })%>"); 

app/views/articles/index.html.erb
  
  <div class="wrap">
    <h2 class="sea-blue">Articles</h2>
    <br>
    <%if current_admin%>
      <%=link_to "Create Article", new_article_path%>
    <%end%>
  </div>
  
  <div class="wrap">
    <table id="ajax-table">
        <%=render partial: 'article_list', locals: {items: @articles}%>
    </table>
    <table id="dates">
      <tr><th>Archives</th></tr>
      <%(@times.length-1).times do |j|%>
        <% if @times[j].strftime('%b %Y') != @times[j+1].strftime('%b %Y')%>
        <tr><td>
          <%=link_to @times[j].strftime('%b %Y'), fetch_articles_path(:time =>@times[j].strftime('%b %Y')), :remote=>true%></td></tr>
        <tr><td>
          <%=link_to @times[j+1].strftime('%b %Y'), fetch_articles_path(:time =>@times[j+1].strftime('%b %Y')), :remote=>true%></td></tr>
        <%end%>
      <%end%>
    </table>
  </div>
  
  <br><br>

app/views/articles/new.html.erb
<%provide(:title, "new")%>
<%= render 'form'%>
<%=link_to "Show Articles", articles_path%>

app/views/articles/next_articles.js.erb
$("#ajax-table").html("<%= escape_javascript(render partial: 
	'article_list', locals: { items: @articles })%>"); 

app/views/articles/previous_articles.js.erb
$("#ajax-table").html("<%= escape_javascript(render partial: 
	'article_list', locals: { items: @articles })%>"); 

app/views/articles/show.html.erb
<div class="wrapper"><h1><%=@article.title%></h1></div>
<br>
<div class="wrapper">
	<div class="photo-gallery">
		<%i=0%>
		<% @photos.each do |photo| %>
		<%if photo.tags!=nil && @article.tags!=nil && @article.tags.split(" ") & photo.tags.split(" ")!=nil  %>
			<% if i<4 %>
			<div class= "gallery-image" id="hide-<%=(i+1).to_s%>" >
				<%=image_tag photo.file_data.url%>
			</div>
			<%i+=1%>
			<%end%>
		<%end%>
	<%end%>
	</div>

	
	<h3><i><%=@article.description%></i>
	</h3><br>
	<br><h4></h4>

	<p>Text:<%=@article.text%><br><br></p><br>
	<%=link_to "back", articles_path%>
	<% if current_admin%>
	<%=link_to 'edit', edit_article_path(@article)  %>
	<%=link_to 'okay', articles_path%>
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true 
  %>
  <%= csrf_meta_tags %>
  		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>GhostRyte</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
</head>

<body>
	<nav id="main">
		<span id="main-label" class="mobile-hide">Jordan Littell</span>

		<ul class ="mobile-hide" id="main-menu">
			<li class="main-item"><%=link_to 'Home', controller: "welcome"%></a></li>
		    <li class="main-item"><%=link_to 'Articles', articles_path%></li>
		    <li class="main-item"><%=link_to 'Photos', photos_path%></li>
		    <li class="main-item"> <%=link_to 'About', admins_path%></li>

		    <% if !current_admin %>
		    <li class="main-item"><%=link_to 'Login', log_in_path%></li>


		    <%end%>
		    <% if current_admin %>
		    	<li class="main-item"><%=link_to 'Logout', log_out_path%></li>
		    	

		    <%end%>
		</ul>

		<span id="mobile-menu-img">Menu</span>
		<ul id="mobile-menu"> 
		    <li class="main-item"><%=link_to 'Home', controller: "welcome"%></a></li>
		    <li class="main-item"><%=link_to 'Articles', articles_path%></li>
		    <li class="main-item"><%=link_to 'Photos', photos_path%></li>
		    <% if !current_admin %>
		    <li class="main-item"><%=link_to 'Login', log_in_path%></li>
		    <%end%>
		    <% if current_admin %>
		    	<li class="main-item"><%=link_to 'Logout', log_out_path%></li>
		    	

		    <%end%>
		
		</ul>
	</nav>
	<div id="nav-clear"></div>
	
<div id="container">
	
	<%flash.each do |key,msg|%>
		<div class=<%=key%>><h2 class="white"><%=msg%></h2></div>
	<%end%>
	<%= yield %>
</div>

</body>
</html>

app/views/photos/_form.html.erb
<%=form_for @photo, :html => {:multipart => "true"} do |f|%>
<h1><%=yield :title%></h1>
<h3><%=f.label :title%></h3>
<%=f.text_field :title%><br>
<%=f.label :tags%>
<%=f.text_field :tags%>
<br>
<br>
<%=f.file_field :file_data%> <br><br>
<%=f.submit :okay%>
<%end%>

app/views/photos/edit.html.erb
<%provide(:title,"Edit Photo")%>
<%=render 'form'%>

app/views/photos/index.html.erb
<div id="container">
	<div class="wrap">
	<h1>Photos</h1>

	<% if current_admin%>
		<%=link_to 'create new', photos_new_path %>
	<%end%>
	</div>
	<br><br><Br>
	<div class="photo-gallery">
		<%=will_paginate @photos%>
		<%@photos.each do |photo| %>
			<%url = photo.file_data.url%>

			<div class="gallery-image">
				<hr>
				<h4><%=photo.title%></h4>
				<img src = <%="#{url}"%> class="gallery-image"/>
				<ul>
					<% if current_admin %>
				<%= link_to "delete",photo_path(photo), :method=>:delete%>
				<%=link_to "edit", edit_photo_path(photo), :method => "get"%>
				<%end%>
				</ul>
			</div>
			<hr>
		<%end%>
	</div>
</div>

app/views/photos/new.html.erb
<%provide(:title,"New Photo")%>
<%= render 'form'%>

app/views/stats/_form.html.erb
<div id="stats-updates">
	<%=form_for @stat do |f| %>
		<h4><%=f.label :hours_slept%></h4><br>
		<%=f.number_field :hours_slept%><br>
		<h4><%=f.label :hours_worked%></h4><br>
		<%=f.number_field :hours_worked%><br>
		<h4><%=f.label :mg_caffeine%></h4><br>
		<%=f.number_field :mg_caffeine%><br>
		<h4><%=f.label :day_rating%></h4><br>
		<%=f.number_field(:day_rating )%><br><br>
		<h4><%=f.label :hours_fitness%></h4><br>
		<%=f.number_field(:hours_fitness )%><br><br>

		<%=f.submit :submit%>
	<%end%>
</div>

app/views/stats/create.html.erb
<div id="stats-updates">
			<%=form_for @stat do |f| %>
				<%=f.label :hours_slept%>
				<%=f.text_field :hours_slept%>
				<%=f.label :hours_worked%>
				<%=f.text_field :hours_worked%>
				<%=f.label :mg_caffeine%>
				<%=f.text_field :mg_caffeine%>
				<%=f.label :day_rating%>
				<%=f.text_field :day_rating%>
			<%end%>
		</div>

app/views/stats/destroy.html.erb
<h1>Stats#destroy</h1>
<p>Find me in app/views/stats/destroy.html.erb</p>

app/views/stats/new.html.erb
<div id="stats-updates">
			<%=form_for @stat do |f| %>
				<h3><%=f.label :hours_slept%></h3><br><br>
				<%=f.text_field :hours_slept%><br><br>
				<h3><%=f.label :hours_worked%></h3><br><br>
				<%=f.text_field :hours_worked%><br><br>
				<h3><%=f.label :mg_caffeine%></h3><br><br>
				<%=f.text_field :mg_caffeine%><br><br>
				<h3><%=f.label :day_rating%></h3><br><br>
				<%=f.text_field :day_rating%><br><br>
			<%end%>
		</div>

app/views/welcome/_list.html.erb
<%@articles.each_with_index do |article,j|%>
	<% if j<4%>
		<%=resource.title%>
	<%else%>
	<%break%>
	<%end%>
<%end%>

app/views/welcome/index.html.erb
		<div id="basque">
			<div class="wrap">
				<div id="updates">
					<h4 class="gold">Recent Activity</h4>
					<ul>
			            <%@articles.each_with_index do |article,j|%>
				            <% if j<4%>
						<%created = ((Time.now-article.created_at)/(24*60)).floor/24%>
				            	<li>Added <%=article.class.to_s.downcase%>: <%=article.title%> <%if created>0%><%=created.to_s%> days ago<%else%>(today)<%end%></li>
				            <%else%>
				            	<%break%>
				            <%end%>
			            <%end%>
			        </ul>
			        <ul>
			            <%@photos.each_with_index do |photo,j|%>
				            <% if j<4%>
				            	<li>Added <%=photo.class.to_s.downcase%>: <%=photo.title%> (<%=((Time.now-photo.created_at)/(24*60)).floor/24%> days ago)</li>
				            <%else%>
				            	<%break%>
				            <%end%>
			            <%end%>
			        </ul>
			        
				</div>
				<div id="header">Welcome!</div>
			</div>
		</div>

		<br>
	
		
			<br>
			<h2 class="gold">A word from the creator:</h2>
			<hr>
			<div class="wrap">
			    <div class="col">
			    	<p>
			        Pellentesque a erat arcu. Nunc adipiscing vulputate faucibus. Etiam et venenatis odio. Ut faucibus pellentesque leo nec sagittis. Fusce congue diam sem, et blandit nisl lobortis in. Nullam quis laoreet nisi. Vivamus ante metus, accumsan nec ipsum et, euismod accumsan purus. Aliquam eu eros posuere, fringilla orci at, luctus turpis. Ut mollis, ipsum sed fringilla semper, turpis magna egestas nisi, aliquam semper nunc magna lobortis risus. Morbi vel iaculis tortor. Sed urna neque, pretium sit amet malesuada sed, venenatis consequat ligula. Vivamus volutpat velit sed nulla imperdiet, in suscipit nisl ornare.</p>
			    </div>

			</div>

		

		<h3 class="light-blue">This is a 3rd level header</h3>
		    <h3 class="gold">This is a 3rd level header</h3>
		    <h3 class="subtle">This is a 3rd level header</h3>
		    <h3 class="sea-blue">This is a 3rd level header</h3>
		<div class="wrap">
		    
		<p>
		Sed semper dictum auctor. Proin nisl augue, venenatis et nulla eget, suscipit gravida lacus. Duis at libero consequat, ultrices arcu vel, lacinia lorem. Nullam dapibus, nunc non placerat gravida, felis augue viverra neque, eu hendrerit eros erat a risus. Duis pretium congue enim. Phasellus in ullamcorper diam. Nulla facilisi. In ut quam consequat, fermentum ante eu, eleifend lectus. Integer porttitor, mi a tristique tincidunt, ipsum libero lacinia orci, sed sodales nibh dolor at dolor.
		</p></div>

		</section>

		<section>
		<h2 class="gold">About this website</h2>
		<hr>
		<div class="wrap">
		    
		 <p> 
		Sed semper dictum auctor. Proin nisl augue, venenatis et nulla eget, suscipit gravida lacus. Duis at libero consequat, ultrices arcu vel, lacinia lorem. Nullam dapibus, nunc non placerat gravida, felis augue viverra neque, eu hendrerit eros erat a risus. Duis pretium congue enim. Phasellus in ullamcorper diam. Nulla facilisi. In ut quam consequat, fermentum ante eu, eleifend lectus. Integer porttitor, mi a tristique tincidunt, ipsum libero lacinia orci, sed sodales nibh dolor at dolor.
		</p> 
		</div>

		</section>

		<section>
		<h5>Header 5</h5>
		<hr>
		<div class="wrap">
		    
		<p>
		Sed semper dictum auctor. Proin nisl augue, venenatis et nulla eget, suscipit gravida lacus. Duis at libero consequat, ultrices arcu vel, lacinia lorem. Nullam dapibus, nunc non placerat gravida, felis augue viverra neque, eu hendrerit eros erat a risus. Duis pretium congue enim. Phasellus in ullamcorper diam. Nulla facilisi. In ut quam consequat, fermentum ante eu, eleifend lectus. Integer porttitor, mi a tristique tincidunt, ipsum libero lacinia orci, sed sodales nibh dolor at dolor.
		</p></div>

		</section>

		<h2 class="sea-blue">About Me</h2><hr>
		<div class="wrap">
		    <div class="col">I am a guy in my mid 20s enjoying life in San Francisco. I love desgining websies and apps, tinkering with electronics, creating music, and art. I graduated with a BS in Mathematics and am now attending App Academy in SF.</div>
		</div>
		<div class="wrap">
		    <nav id="icon-list">
		    
		        <ul id="icon-menu">
		            <li><span data-icon="&#xe601" class="icon" id="github"></span></li>
		            <li><span data-icon="&#xe602" class="icon" id="linked-in"></span></li>
		            <li><span data-icon="&#xe603" class="icon" id="google"></span></li>
		            <li><span data-icon="&#xe60c" class="icon" id="mail"></span></li>
		        </ul>
		    </nav>

		</div><br><br>
		<h1 class="sea-blue">Words of Wisdom</h1>
		<div class="wrap">
			
		        <span class="quote"><q>I learned this, at least, by my experiment: that if one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.</q>
		        <br><br>
		        --Henry David Thoreau</span>  
		       
		</div>
		<div id="loading" data-icon="&#xe606" class="icon"></div>

	</div>
            